package correlator

import (
	"crypto/sha256"
	"fmt"
	"time"

	"nameless/internal/core"
)

// RelationType describes how two entities are connected.
type RelationType string

const (
	// RelEmailToRegistration links an email to a platform where it was found registered.
	// Generated by Rule A: crawler email → emailcheck result.
	RelEmailToRegistration RelationType = "email_to_registration"

	// RelEmailToUsername links an email's local-part to a candidate username.
	// Generated by Rule B: local-part extraction.
	RelEmailToUsername RelationType = "email_to_username"

	// RelUsernameToProfile links a username to a platform profile found by username module.
	// Generated by Rule B's downstream username check.
	RelUsernameToProfile RelationType = "username_to_profile"

	// RelSubdomainToCrawl links a subdomain to content discovered by re-crawling it.
	// Generated by Rule C: harvester subdomain → re-crawl.
	RelSubdomainToCrawl RelationType = "subdomain_to_crawl"
)

// Confidence represents how certain a relation is.
// Values are defined as named constants to avoid magic floats in code.
//
// Confidence is a property of the Relation (the edge), not the Entity (the node).
// The same entity can participate in relations with different confidence levels
// depending on how the relation was derived.
type Confidence float32

const (
	// ConfidenceObserved is assigned to data directly returned by an external
	// source (e.g. username found on GitHub, email found in crt.sh record).
	ConfidenceObserved Confidence = 1.0

	// ConfidenceInferredHigh is assigned to correlations with strong evidence
	// (e.g. email found on a crawled page of the target domain → emailcheck).
	ConfidenceInferredHigh Confidence = 0.8

	// ConfidenceInferredMid is assigned to probabilistic correlations where the
	// link is plausible but not certain (e.g. email local-part → username candidate).
	ConfidenceInferredMid Confidence = 0.6

	// ConfidenceInferredLow is assigned to speculative correlations
	// (e.g. DNS brute-force subdomain not yet re-verified, re-crawl of harvested subdomain).
	ConfidenceInferredLow Confidence = 0.5
)

// Relation describes a directed edge between two Entities in the correlation graph.
// A Relation is generated by the correlator, not by individual scan modules.
type Relation struct {
	// ID is a stable, content-derived identifier for this relation.
	ID string `json:"id"`

	// Type classifies what kind of connection this relation represents.
	Type RelationType `json:"type"`

	// FromID is the Entity.ID of the source node.
	FromID string `json:"from_id"`
	// FromValue is a human-readable copy of the source entity's value,
	// included for readability in JSON/HTML output without requiring a join.
	FromValue string `json:"from_value"`

	// ToID is the Entity.ID of the destination node.
	ToID string `json:"to_id"`
	// ToValue is a human-readable copy of the destination entity's value.
	ToValue string `json:"to_value"`

	// Confidence indicates how certain this relation is.
	// See Confidence constants for the four tiers and their rationale.
	Confidence Confidence `json:"confidence"`

	// DiscoveredBy names the rule (e.g. "rule_a_email_emailcheck") that produced
	// this relation. Useful for debugging and output filtering.
	DiscoveredBy string `json:"discovered_by"`

	Timestamp time.Time `json:"timestamp"`
}

// NewRelation constructs a Relation with a stable, content-derived ID.
func NewRelation(
	relType RelationType,
	from, to core.Entity,
	confidence Confidence,
	discoveredBy string,
) Relation {
	id := relationID(relType, from.ID, to.ID)
	return Relation{
		ID:           id,
		Type:         relType,
		FromID:       from.ID,
		FromValue:    from.Value,
		ToID:         to.ID,
		ToValue:      to.Value,
		Confidence:   confidence,
		DiscoveredBy: discoveredBy,
		Timestamp:    time.Now().UTC(),
	}
}

// relationID derives a stable identifier from the relation's type and endpoint IDs.
func relationID(t RelationType, fromID, toID string) string {
	h := sha256.Sum256([]byte(string(t) + ":" + fromID + ":" + toID))
	return fmt.Sprintf("%x", h[:8])
}

// RelationStore is a thread-safe collection of Relations produced by the correlator.
// Unlike Aggregator (which is written to during scanning), RelationStore is
// written to only during the post-processing correlation pass and read during output.
type RelationStore struct {
	relations map[string]Relation // keyed by Relation.ID for dedup
}

// NewRelationStore returns an empty RelationStore.
func NewRelationStore() *RelationStore {
	return &RelationStore{relations: make(map[string]Relation)}
}

// Add inserts a relation. Duplicate relation IDs are silently ignored (first-write-wins).
func (s *RelationStore) Add(r Relation) {
	if _, exists := s.relations[r.ID]; !exists {
		s.relations[r.ID] = r
	}
}

// All returns a slice of all relations in the store.
func (s *RelationStore) All() []Relation {
	out := make([]Relation, 0, len(s.relations))
	for _, r := range s.relations {
		out = append(out, r)
	}
	return out
}

// Len returns the number of unique relations stored.
func (s *RelationStore) Len() int { return len(s.relations) }
